# Generated by Django 5.0.6 on 2024-06-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_event_type_remove_trigger_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativemeasurementtrigger',
            name='operator',
            field=models.CharField(choices=[('gt', '> (Greater Than)'), ('gte', '>= (Greater Than or Equal)'), ('lt', '< (Less Than)'), ('lte', '<= (Less Than or Equal)'), ('exact', '== (Equal)'), ('ne', '!= (Not Equal)')], max_length=5),
        ),
        migrations.AlterField(
            model_name='instantmeasurementtrigger',
            name='active_threshold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='category',
            field=models.IntegerField(choices=[(1, 'Voltage'), (2, 'Connection'), (3, 'Consumption'), (4, 'Generation'), (5, 'Measurement'), (6, 'Other')]),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')]),
        ),
    ]
