# Generated by Django 5.0.6 on 2024-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_cumulativemeasurementtrigger_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantmeasurementtrigger',
            name='active_threshold',
        ),
        migrations.RemoveField(
            model_name='instantmeasurementtrigger',
            name='deactivate_threshold',
        ),
        migrations.AddField(
            model_name='instantmeasurementtrigger',
            name='lower_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instantmeasurementtrigger',
            name='upper_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='cumulativemeasurementtrigger',
            name='adjustment_factor',
        ),
        migrations.RemoveField(
            model_name='cumulativemeasurementtrigger',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='instantmeasurementtrigger',
            name='operator',
        ),
        migrations.AddField(
            model_name='cumulativemeasurementtrigger',
            name='lower_threshold_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cumulativemeasurementtrigger',
            name='upper_threshold_percent',
            field=models.FloatField(default=0),
        ),
    ]
