# Generated by Django 3.0.14 on 2023-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('researcher', 'Researcher'), ('general', 'General User')], default='general', max_length=20),
        ),
    ]
