# Generated by Django 2.1.5 on 2019-04-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190429_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manageruser',
            options={'verbose_name': 'Manager'},
        ),
    ]
