# Generated by Django 2.1.5 on 2019-05-06 18:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0006_auto_20190429_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageruser',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='researcheruser',
            name='customuser_ptr',
        ),
        migrations.DeleteModel(
            name='ManagerUser',
        ),
        migrations.DeleteModel(
            name='ResearcherUser',
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherUser',
            fields=[
            ],
            options={
                'verbose_name': 'Researcher',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
