# Generated by Django 2.1.5 on 2019-05-08 13:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_auto_20190508_1019'),
        ('admin', '0004_auto_20190508_1019'),
        ('users', '0008_auto_20190508_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageruser',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='researcheruser',
            name='customuser_ptr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('rsc', 'researcher'), ('man', 'manager'), ('adm', 'admin')], default='man', max_length=3),
        ),
        migrations.DeleteModel(
            name='ManagerUser',
        ),
        migrations.DeleteModel(
            name='ResearcherUser',
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Manager',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherUser',
            fields=[
            ],
            options={
                'verbose_name': 'Researcher',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
