# Generated by Django 2.1.5 on 2019-05-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190508_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerUser',
        ),
        migrations.DeleteModel(
            name='ResearcherUser',
        ),
    ]
