# Generated by Django 3.0.2 on 2020-04-07 08:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='This field is required', verbose_name='details')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.event_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'event',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRelatedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
                ('consumption', models.FloatField(default=0.0, verbose_name='consumption related')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='FailedConnectionSlaveEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
            ],
            options={
                'verbose_name': 'failed connection with slave server',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='FailedConnectionTransductorEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
            ],
            options={
                'verbose_name': 'failed connection with meter',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='VoltageRelatedEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event')),
            ],
            options={
                'verbose_name': 'voltage related',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='ConsumptionAboveContract',
            fields=[
                ('consumptionrelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.ConsumptionRelatedEvent')),
            ],
            options={
                'verbose_name': 'consumption above contracted threshold',
            },
            bases=('events.consumptionrelatedevent',),
        ),
        migrations.CreateModel(
            name='ConsumptionPeakEvent',
            fields=[
                ('consumptionrelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.ConsumptionRelatedEvent')),
            ],
            options={
                'verbose_name': 'consumption peak',
            },
            bases=('events.consumptionrelatedevent',),
        ),
        migrations.CreateModel(
            name='CriticalVoltageEvent',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'verbose_name': 'critical voltage',
            },
            bases=('events.voltagerelatedevent',),
        ),
        migrations.CreateModel(
            name='PhaseDropEvent',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'verbose_name': 'phase drop',
            },
            bases=('events.voltagerelatedevent',),
        ),
        migrations.CreateModel(
            name='PrecariousVoltageEvent',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'verbose_name': 'precarious voltage',
            },
            bases=('events.voltagerelatedevent',),
        ),
    ]
