# Generated by Django 2.1.5 on 2020-01-09 18:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transductors', '0002_auto_20190930_0943'),
        ('slaves', '0002_auto_20200106_1553'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedConnectionSlaveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.failedconnectionslaveevent_set+', to='contenttypes.ContentType')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_failedconnectionslaveevent', to='slaves.Slave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailedConnectionTransductorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.failedconnectiontransductorevent_set+', to='contenttypes.ContentType')),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_failedconnectiontransductorevent', to='transductors.EnergyTransductor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoltageRelatedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('measures', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriticalVoltageEvent',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.voltagerelatedevent',),
        ),
        migrations.CreateModel(
            name='PhaseDropEvent',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.voltagerelatedevent',),
        ),
        migrations.CreateModel(
            name='PrecariousVoltageEvent',
            fields=[
                ('voltagerelatedevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.VoltageRelatedEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('events.voltagerelatedevent',),
        ),
        migrations.AddField(
            model_name='voltagerelatedevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.voltagerelatedevent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='voltagerelatedevent',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_voltagerelatedevent', to='transductors.EnergyTransductor'),
        ),
    ]
