# Generated by Django 3.0.2 on 2020-04-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transductors', '0001_initial'),
        ('slaves', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltagerelatedevent',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='events_voltagerelatedevent', to='transductors.EnergyTransductor', verbose_name='meter'),
        ),
        migrations.AddField(
            model_name='failedconnectiontransductorevent',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='events_failedconnectiontransductorevent', to='transductors.EnergyTransductor', verbose_name='meter'),
        ),
        migrations.AddField(
            model_name='failedconnectionslaveevent',
            name='slave',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='events_failedconnectionslaveevent', to='slaves.Slave', verbose_name='slave'),
        ),
    ]
