# Generated by Django 2.1.5 on 2020-01-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedconnectionslaveevent',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedconnectiontransductorevent',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voltagerelatedevent',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
