# Generated by Django 2.1.5 on 2020-01-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0002_auto_20190930_0943'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalvoltageevent',
            name='transductor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events_criticalvoltageevent', to='transductors.EnergyTransductor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phasedropevent',
            name='transductor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events_phasedropevent', to='transductors.EnergyTransductor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precariousvoltageevent',
            name='transductor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events_precariousvoltageevent', to='transductors.EnergyTransductor'),
            preserve_default=False,
        ),
    ]
