# Generated by Django 2.1.5 on 2020-01-15 01:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_auto_20200113_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_events.event_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='criticalvoltageevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='failedconnectionslaveevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='failedconnectiontransductorevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='phasedropevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='precariousvoltageevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='voltagerelatedevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='failedconnectionslaveevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='failedconnectionslaveevent',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='failedconnectionslaveevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='failedconnectionslaveevent',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='failedconnectiontransductorevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='failedconnectiontransductorevent',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='failedconnectiontransductorevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='failedconnectiontransductorevent',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='voltagerelatedevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voltagerelatedevent',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='voltagerelatedevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voltagerelatedevent',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='failedconnectionslaveevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedconnectiontransductorevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voltagerelatedevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
    ]
