# Generated by Django 2.1.5 on 2020-01-21 10:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200120_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
