# Generated by Django 3.0.2 on 2020-01-29 15:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0009_auto_20200129_1542'),
        ('slaves', '0004_auto_20200129_1503'),
        ('events', '0008_auto_20200121_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionabovecontract',
            options={'verbose_name': 'consumption above contracted threshold event'},
        ),
        migrations.AlterModelOptions(
            name='consumptionpeakevent',
            options={'verbose_name': 'consumption peak event'},
        ),
        migrations.AlterModelOptions(
            name='criticalvoltageevent',
            options={'verbose_name': 'critical voltage event'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event'},
        ),
        migrations.AlterModelOptions(
            name='failedconnectionslaveevent',
            options={'verbose_name': 'failed connection with slave server event'},
        ),
        migrations.AlterModelOptions(
            name='failedconnectiontransductorevent',
            options={'verbose_name': 'failed connection with meter event'},
        ),
        migrations.AlterModelOptions(
            name='phasedropevent',
            options={'verbose_name': 'phase drop event'},
        ),
        migrations.AlterModelOptions(
            name='precariousvoltageevent',
            options={'verbose_name': 'precarious voltage event'},
        ),
        migrations.AlterModelOptions(
            name='voltagerelatedevent',
            options={'verbose_name': 'voltage related event'},
        ),
        migrations.AlterField(
            model_name='consumptionrelatedevent',
            name='consumption',
            field=models.FloatField(default=0.0, verbose_name='consumption related event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ended at'),
        ),
        migrations.AlterField(
            model_name='failedconnectionslaveevent',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_failedconnectionslaveevent', to='slaves.Slave', verbose_name='slave'),
        ),
        migrations.AlterField(
            model_name='failedconnectiontransductorevent',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_failedconnectiontransductorevent', to='transductors.EnergyTransductor', verbose_name='meter'),
        ),
        migrations.AlterField(
            model_name='voltagerelatedevent',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_voltagerelatedevent', to='transductors.EnergyTransductor', verbose_name='meter'),
        ),
    ]
