version: '3.9'
services:
    master-db:
        container_name: master-db
        restart: unless-stopped
        image: postgres:15.2-bullseye
        env_file: dev-env
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - pg-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5m
            timeout: 30s
            retries: 3
            start_period: 1m
        networks:
            - master-network

    master-api:
        container_name: master-api
        restart: unless-stopped
        image: ${RELEASE_IMAGE:-master-api}
        build:
            context: .
            dockerfile: Dockerfile
        env_file: dev-env
        command: ['sh', 'scripts/start-dev.sh']
        ports:
            - 443:8001
        networks:
            - sige-network
            - master-network
        volumes:
            - .:/sige-master
            - pip_cache:/usr/local/lib/python3.11/site-packages
        depends_on:
            - master-db

    # pgadmin:
    #     container_name: pgadmin
    #     restart: unless-stopped
    #     image: dpage/pgadmin4
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=admin
    #         - PGADMIN_CONFIG_SERVER_MODE=False
    #     ports:
    #         - 8080:80
    #     networks:
    #         - master-network

volumes:
    pg-data:
        name: master-pgdata
    pip_cache:
        name: master-pip-cache

networks:
    master-network:
        name: master-network
    sige-network:
        driver: bridge
        name: sige-network
