version: '3.9'
services:
    sige-db:
        container_name: sige-db
        restart: unless-stopped
        image: postgres:15.2-bullseye
        env_file:
            - ./.envs/.env.dev
        expose:
            - "5432"
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - sige-dev-pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5m
            timeout: 30s
            retries: 3
            start_period: 1m
        networks:
            - api-network

    sige-api:
        container_name: sige-api
        restart: unless-stopped
        image: ${BI_PATH:-sige-api:latest}
        env_file:
            - ./.envs/.env.dev
        build:
            context: .
            dockerfile: Dockerfile
        command: ['sh', 'scripts/start-dev.sh']
        expose:
            - "8001"
        ports:
            - 8001:8001
        networks:
            - api-network
            - proxy-network
        volumes:
            - .:/sige-master
        depends_on:
            - sige-db

volumes:
    sige-dev-pgdata:
        name: sige-dev-pgdata

networks:
    api-network:
        name: api-network
        driver: bridge
    proxy-network:
        name: proxy-network
        driver: bridge
        # external: true
