version: '3.7'
services:
    master-db:
        container_name: master-db
        image: postgres:9.6
        ports:
            - 5431:5432
        env_file: dev-env
        networks:
            - smi-network
        volumes:
            - master-pg-data:/var/lib/postgresql/data

    master-api:
        container_name: master-api
        build: .
        env_file: dev-env
        command: ["sh", "scripts/start.sh"]
        ports:
            - 8001:8001
        networks:
          - smi-network
        volumes:
            - .:/smi-master
            - pip_cache:/usr/local/lib/python3.6/site-packages
        depends_on:
            - master-db

volumes:
    master-pg-data: {}
    pip_cache:

networks:
  smi-network:
    external: true
