version: '3.9'
services:
    master-db:
        restart: unless-stopped
        image: postgres:15.2-bullseye
        env_file: dev-env
        volumes:
            - master-pg-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 30s
            timeout: 5s
            retries: 5
        networks:
            - master-network

    master-api:
        restart: unless-stopped
        container_name: master-api
        image: registry.gitlab.com/lappis-unb/projects/smi/smi-master
        build:
            context: .
            dockerfile: Dockerfile
        env_file: dev-env
        command: [ "sh", "scripts/start.sh" ]
        ports:
            - 8001:8001
        networks:
            - smi-network
            - master-network
        volumes:
            - .:/smi-master
            - pip_cache:/usr/local/lib/python3.11/site-packages
        depends_on:
            master-db:
                condition: service_healthy

volumes:
    master-pg-data:
    pip_cache:


networks:
    master-network:
    smi-network:
        driver: bridge
