# Generated by Django 2.1.5 on 2019-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transductormodel',
            name='serial_protocol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transductormodel',
            name='transport_protocol',
            field=models.CharField(default='', max_length=50),
        ),
    ]
