# Generated by Django 2.1.5 on 2019-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_models', '0002_auto_20190422_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transductormodel',
            name='serial_protocol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transductormodel',
            name='transport_protocol',
            field=models.CharField(max_length=50),
        ),
    ]
