# Generated by Django 2.1.5 on 2019-06-03 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_models', '0003_auto_20190422_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transductormodel',
            name='minutely_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='transductormodel',
            name='monthly_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
        ),
        migrations.AddField(
            model_name='transductormodel',
            name='quarterly_register_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=None, size=None),
        ),
    ]
