# Generated by Django 2.1.5 on 2019-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductor_models', '0004_auto_20190603_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transductormodel',
            name='id',
        ),
        migrations.AddField(
            model_name='transductormodel',
            name='model_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
