# Generated by Django 3.0.2 on 2020-04-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('measurements', '0001_initial'),
        ('transductors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimemeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_realtimemeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.quarterlymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_quarterlymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.monthlymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_monthlymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.minutelymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_minutelymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
    ]
