# Generated by Django 2.1.5 on 2019-09-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('transductors', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements_quarterlymeasurement', to='transductors.EnergyTransductor'),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.monthlymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements_monthlymeasurement', to='transductors.EnergyTransductor'),
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.minutelymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='transductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements_minutelymeasurement', to='transductors.EnergyTransductor'),
        ),
    ]
