# Generated by Django 3.0.2 on 2020-04-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transductors', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_peak', models.FloatField(default=0, verbose_name='Tax value to periods in peak time')),
                ('value_off_peak', models.FloatField(default=0, verbose_name='Tax value to periods in off peak time')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='registration date')),
            ],
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.minutelymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='minutelymeasurement',
            name='transductor',
            field=models.ForeignKey(default=None, help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_minutelymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.monthlymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='transductor',
            field=models.ForeignKey(default=None, help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_monthlymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.quarterlymeasurement_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='transductor',
            field=models.ForeignKey(default=None, help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_quarterlymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimemeasurement',
            name='transductor',
            field=models.ForeignKey(default=None, help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_realtimemeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.Tax', verbose_name='Tax for peak time collection'),
        ),
    ]
