# Generated by Django 3.0.2 on 2020-04-16 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20200409_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax'},
        ),
        migrations.AlterField(
            model_name='tax',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 43, 55, 269968), verbose_name='registration date'),
        ),
    ]
