# Generated by Django 2.1.5 on 2019-12-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0002_auto_20190930_0943'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('measurements', '0002_auto_20190924_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField()),
                ('voltage_a', models.FloatField(default=0)),
                ('voltage_b', models.FloatField(default=0)),
                ('voltage_c', models.FloatField(default=0)),
                ('current_a', models.FloatField(default=0)),
                ('current_b', models.FloatField(default=0)),
                ('current_c', models.FloatField(default=0)),
                ('total_active_power', models.FloatField(default=0)),
                ('total_reactive_power', models.FloatField(default=0)),
                ('total_power_factor', models.FloatField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_measurements.realtimemeasurement_set+', to='contenttypes.ContentType')),
                ('transductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements_realtimemeasurement', to='transductors.EnergyTransductor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
