# Generated by Django 3.0.2 on 2020-04-16 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20200416_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 45, 39, 623963), verbose_name='registration date'),
        ),
    ]
