# Generated by Django 3.0.2 on 2020-02-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_realtimemeasurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutelymeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='monthlymeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='quarterlymeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='realtimemeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
    ]
