# Generated by Django 3.0.2 on 2020-01-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0011_auto_20200129_1635'),
        ('measurements', '0004_auto_20200129_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutelymeasurement',
            name='collection_time',
            field=models.DateTimeField(help_text='This field is required', verbose_name='Collection time'),
        ),
        migrations.AlterField(
            model_name='minutelymeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_minutelymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='collection_time',
            field=models.DateTimeField(help_text='This field is required', verbose_name='Collection time'),
        ),
        migrations.AlterField(
            model_name='monthlymeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_monthlymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='collection_time',
            field=models.DateTimeField(help_text='This field is required', verbose_name='Collection time'),
        ),
        migrations.AlterField(
            model_name='quarterlymeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_quarterlymeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
        migrations.AlterField(
            model_name='realtimemeasurement',
            name='collection_time',
            field=models.DateTimeField(help_text='This field is required', verbose_name='Collection time'),
        ),
        migrations.AlterField(
            model_name='realtimemeasurement',
            name='transductor',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, related_name='measurements_realtimemeasurement', to='transductors.EnergyTransductor', verbose_name='Energy meter'),
        ),
    ]
