# Generated by Django 3.0.2 on 2020-04-20 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_auto_20200416_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 19, 27, 10, 202249), verbose_name='registration date'),
        ),
    ]
