# Generated by Django 3.0.2 on 2020-02-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_auto_20200129_1635'),
        ('measurements', '0004_auto_20200211_1659'),
    ]

    operations = [
    ]
