# Generated by Django 3.0.2 on 2020-09-16 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_auto_20200420_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
    ]
