# Generated by Django 3.0.2 on 2020-02-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_merge_20200217_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutelymeasurement',
            old_name='collection_date',
            new_name='collection_time',
        ),
        migrations.RenameField(
            model_name='monthlymeasurement',
            old_name='collection_date',
            new_name='collection_time',
        ),
        migrations.RenameField(
            model_name='quarterlymeasurement',
            old_name='collection_date',
            new_name='collection_time',
        ),
        migrations.RenameField(
            model_name='realtimemeasurement',
            old_name='collection_date',
            new_name='collection_time',
        ),
    ]
