# Generated by Django 3.0.2 on 2020-02-18 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_auto_20200217_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlymeasurement',
            options={'verbose_name': 'Measurement'},
        ),
        migrations.RenameField(
            model_name='minutelymeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='monthlymeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='quarterlymeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RenameField(
            model_name='realtimemeasurement',
            old_name='collection_time',
            new_name='collection_date',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='active_max_power_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='active_max_power_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='capacitive_power_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='capacitive_power_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='consumption_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='consumption_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='generated_energy_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='generated_energy_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='inductive_power_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='inductive_power_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='reactive_max_power_off_peak_time',
        ),
        migrations.RemoveField(
            model_name='monthlymeasurement',
            name='reactive_max_power_peak_time',
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='active_max_power_list_off_peak_time1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='active_max_power_list_peak_time1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='active_max_power_off_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='active_max_power_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='capacitive_power_off_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='capacitive_power_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='consumption_off_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='consumption_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='generated_energy_off_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='generated_energy_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='inductive_power_off_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='inductive_power_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_off_peak_time1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='reactive_max_power_list_peak_time1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=None, size=None),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='reactive_max_power_off_peak_time1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlymeasurement',
            name='reactive_max_power_peak_time1',
            field=models.FloatField(default=0),
        ),
    ]
