# Generated by Django 3.0.14 on 2023-02-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_auto_20200916_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlymeasurement',
            options={'verbose_name': 'Monthly measurement'},
        ),
    ]
