# Generated by Django 3.0.2 on 2020-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0009_auto_20200218_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Tax value')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='registration date')),
            ],
        ),
    ]
