# Generated by Django 3.0.2 on 2020-03-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0010_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.Tax', verbose_name='Tax for peak time collection'),
        ),
    ]
