# Generated by Django 3.0.2 on 2020-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0011_quarterlymeasurement_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='value',
            field=models.FloatField(default=0, verbose_name='Tax value'),
        ),
    ]
