# Generated by Django 3.0.2 on 2020-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0012_auto_20200306_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='value',
        ),
        migrations.AddField(
            model_name='tax',
            name='value_peak',
            field=models.FloatField(default=0, verbose_name='Tax value to periods in off peak time'),
        ),
    ]
