# Generated by Django 3.0.2 on 2020-03-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0013_auto_20200306_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='value_off_peak',
            field=models.FloatField(default=0, verbose_name='Tax value to periods in off peak time'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='value_peak',
            field=models.FloatField(default=0, verbose_name='Tax value to periods in peak time'),
        ),
    ]
