# Generated by Django 3.0.2 on 2020-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0014_auto_20200306_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterlymeasurement',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
