# Generated by Django 3.0.2 on 2020-03-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0015_auto_20200319_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_peak', models.FloatField(default=0, verbose_name='Tax value to periods in peak time')),
                ('value_off_peak', models.FloatField(default=0, verbose_name='Tax value to periods in off peak time')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='registration date')),
            ],
        ),
        migrations.AddField(
            model_name='quarterlymeasurement',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.Tax', verbose_name='Tax for peak time collection'),
        ),
    ]
