# Generated by Django 3.0.2 on 2020-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='This field is required', max_length=50, verbose_name='IP address')),
                ('port', models.CharField(default='80', max_length=5, verbose_name='IP access port')),
                ('name', models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Location')),
                ('broken', models.BooleanField(default=False, verbose_name='Broken')),
            ],
            options={
                'verbose_name': 'Slave server',
            },
        ),
    ]
