# Generated by Django 2.1.5 on 2019-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
