# Generated by Django 3.0.2 on 2020-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
