# Generated by Django 2.1.5 on 2019-09-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slaves', '0001_initial'),
        ('transductors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='transductors',
            field=models.ManyToManyField(related_name='slave_servers', to='transductors.EnergyTransductor'),
        ),
    ]
