# Generated by Django 2.1.5 on 2019-04-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slave',
            name='transductor_list',
        ),
        migrations.AddField(
            model_name='slave',
            name='broken',
            field=models.BooleanField(default=True),
        ),
    ]
