# Generated by Django 3.0.2 on 2020-01-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0003_auto_20200113_1306'),
        ('slaves', '0002_auto_20191213_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slave',
            options={'verbose_name': 'Slave server'},
        ),
        migrations.AlterField(
            model_name='slave',
            name='broken',
            field=models.BooleanField(default=False, verbose_name='Broken'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='ip_address',
            field=models.CharField(max_length=50, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='port',
            field=models.CharField(default='80', max_length=5, verbose_name='IP access port'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='transductors',
            field=models.ManyToManyField(related_name='slave_servers', to='transductors.EnergyTransductor', verbose_name='Meters'),
        ),
    ]
