# Generated by Django 2.1.5 on 2020-01-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0002_auto_20200106_1553'),
        ('slaves', '0002_auto_20191213_2036'),
    ]

    operations = [
    ]
