# Generated by Django 2.1.5 on 2019-04-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0003_auto_20190422_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
