# Generated by Django 2.1.5 on 2019-05-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0003_auto_20190520_1113'),
        ('slaves', '0004_auto_20190422_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='transductors',
            field=models.ManyToManyField(related_name='slave_servers', to='transductors.EnergyTransductor'),
        ),
    ]
