# Generated by Django 3.0.2 on 2020-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0011_auto_20200129_1635'),
        ('slaves', '0004_auto_20200129_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='ip_address',
            field=models.CharField(help_text='This field is required', max_length=50, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='location',
            field=models.CharField(help_text='This field is required', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='transductors',
            field=models.ManyToManyField(help_text='This field is required', related_name='slave_servers', to='transductors.EnergyTransductor', verbose_name='Meters'),
        ),
    ]
