# Generated by Django 3.0.2 on 2020-03-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0005_auto_20200129_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slave',
            name='transductors',
        ),
    ]
