# Generated by Django 2.1.5 on 2019-06-24 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0005_slave_transductors'),
    ]

    operations = [
        migrations.AddField(
            model_name='slave',
            name='port',
            field=models.CharField(default='80', max_length=5),
        ),
        migrations.AlterField(
            model_name='slave',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15, validators=[django.core.validators.RegexValidator('^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$', 'Incorrect IP address format')]),
        ),
    ]
