# Generated by Django 3.0.2 on 2020-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0006_remove_slave_transductors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slave',
            name='location',
        ),
        migrations.AddField(
            model_name='slave',
            name='name',
            field=models.CharField(default='Unnamede', help_text='This field is required', max_length=50, verbose_name='Location'),
        ),
    ]
