# Generated by Django 3.0.2 on 2020-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0007_auto_20200304_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='name',
            field=models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Location'),
        ),
    ]
