# Generated by Django 2.1.5 on 2019-09-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0006_auto_20190617_0900'),
        ('slaves', '0007_auto_20190805_1121'),
    ]

    operations = [
    ]
