# Generated by Django 2.1.5 on 2019-10-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0009_auto_20190902_1549'),
        ('slaves', '0006_auto_20190805_1108'),
    ]

    operations = [
    ]
