# Generated by Django 2.1.5 on 2019-10-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0011_auto_20190919_1654'),
        ('slaves', '0011_auto_20191003_1630'),
    ]

    operations = [
    ]
