# Generated by Django 3.0.2 on 2020-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Name')),
                ('acronym', models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Acronym')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
    ]
