# Generated by Django 2.1.5 on 2019-04-29 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('acronym', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2,}\\) \\d{4,}\\-\\d{4}$', 'Invalid phone format')])),
                ('address', models.CharField(max_length=50, unique=True)),
                ('website_address', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^(https?:\\/\\/)?(www\\.)?([a-zA-Z0-9]+(-?[a-zA-Z0-9])*\\.)+[\\w]{2,}(\\/\\S*)?$', 'Invalid website format')])),
            ],
        ),
    ]
