# Generated by Django 3.0.2 on 2020-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='geolocation_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='campus',
            name='geolocation_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='campus',
            name='zoom_ratio',
            field=models.DecimalField(decimal_places=0, default=16, max_digits=2, verbose_name='map zoom'),
        ),
    ]
