# Generated by Django 2.1.5 on 2020-01-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campus'},
        ),
    ]
