# Generated by Django 3.0.2 on 2020-01-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campus'},
        ),
    ]
