# Generated by Django 2.1.5 on 2019-04-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='website_addres',
            new_name='website_address',
        ),
    ]
