# Generated by Django 2.1.5 on 2019-04-22 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='website_address',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^(https?:\\/\\/)?(www\\.)?([a-zA-Z0-9]+(-?[a-zA-Z0-9])*\\.)+[\\w]{2,}(\\/\\S*)?$', 'Invalid phone format')]),
        ),
    ]
