# Generated by Django 3.0.2 on 2021-03-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0002_auto_20200409_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('regular_tariff', models.FloatField(max_length=10)),
                ('high_tariff', models.FloatField(max_length=10)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campi.Campus')),
            ],
            options={
                'unique_together': {('start_date', 'campus')},
            },
        ),
    ]
