# Generated by Django 2.1.5 on 2019-04-22 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0002_auto_20190422_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^\\(\\d{2,}\\) \\d{4,}\\-\\d{4}$', 'Invalid phone format')]),
        ),
        migrations.AlterField(
            model_name='campus',
            name='website_address',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^(https?:\\/\\/)?(www\\.)?([a-zA-Z0-9]+(-?[a-zA-Z0-9])*\\.)+[\\w]{2,}(\\/\\S*)?$', 'Invalid website format')]),
        ),
    ]
