# Generated by Django 3.0.2 on 2020-01-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0002_auto_20200121_1629'),
        ('campi', '0002_auto_20200122_1018'),
    ]

    operations = [
    ]
