# Generated by Django 3.0.2 on 2020-01-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0003_auto_20200128_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='acronym',
            field=models.CharField(max_length=50, unique=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
