# Generated by Django 3.0.2 on 2020-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0003_merge_20200122_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.RemoveField(
            model_name='campus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='website_address',
        ),
        migrations.AlterField(
            model_name='campus',
            name='acronym',
            field=models.CharField(max_length=50, unique=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
