# Generated by Django 3.0.14 on 2023-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0003_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Verde', 'Verde'), ('Azul', 'Azul')], default='Azul', max_length=10, verbose_name='contract type'),
        ),
        migrations.AddField(
            model_name='campus',
            name='off_peak_demand',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='off peak demand'),
        ),
        migrations.AddField(
            model_name='campus',
            name='peak_demand',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='peak demand'),
        ),
    ]
