# Generated by Django 3.0.2 on 2020-01-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0002_auto_20200121_1049'),
        ('campi', '0003_merge_20200122_1023'),
    ]

    operations = [
    ]
