# Generated by Django 2.1.5 on 2019-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0003_auto_20190415_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='campus',
            name='website_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
