# Generated by Django 3.0.2 on 2020-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0004_auto_20200129_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='acronym',
            field=models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
