# Generated by Django 2.1.5 on 2019-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0004_auto_20190417_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='campus',
            name='website_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
