# Generated by Django 3.0.2 on 2020-02-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0005_auto_20200129_1635'),
        ('campi', '0002_auto_20200121_1049'),
    ]

    operations = [
    ]
