# Generated by Django 3.0.2 on 2020-02-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0006_merge_20200203_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
    ]
