# Generated by Django 3.0.2 on 2020-02-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0007_auto_20200203_1351'),
        ('campi', '0004_merge_20200130_0927'),
    ]

    operations = [
    ]
