# Generated by Django 3.0.2 on 2020-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0008_merge_20200204_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='geolocation_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='campus',
            name='geolocation_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
