# Generated by Django 3.0.2 on 2020-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0010_campus_zoom_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='zoom_ratio',
            field=models.DecimalField(decimal_places=0, default=16, max_digits=2, verbose_name='map zoom'),
        ),
    ]
