# Generated by Django 3.0.2 on 2020-04-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Grouping type',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This field is required', max_length=50, unique=True, verbose_name='Name')),
                ('type', models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, to='groups.GroupType', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Grouping',
            },
        ),
    ]
