# Generated by Django 2.1.5 on 2019-04-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('acronym', models.CharField(max_length=30, unique=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campi.Campus')),
            ],
        ),
    ]
