# Generated by Django 2.1.5 on 2019-09-24 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2,}\\) \\d{4,}\\-\\d{4}$', 'Invalid phone format')])),
                ('name', models.CharField(max_length=120)),
                ('acronym', models.CharField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campi.Campus')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('campus', 'name'), ('campus', 'acronym')},
        ),
    ]
