# Generated by Django 2.1.5 on 2019-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
