# Generated by Django 2.1.5 on 2019-04-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20190422_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campi.Campus'),
        ),
    ]
