# Generated by Django 2.1.5 on 2019-04-22 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20190422_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('^\\(\\d{2,}\\) \\d{4,}\\-\\d{4}$', 'Invalid phone format')]),
        ),
    ]
