# Generated by Django 2.1.5 on 2019-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20190422_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
