# Generated by Django 2.1.5 on 2019-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0004_auto_20190422_1246'),
        ('buildings', '0006_auto_20190423_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='acronym',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('campus', 'name'), ('campus', 'acronym')},
        ),
    ]
