# Generated by Django 2.1.5 on 2019-04-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transductor_models', '0003_auto_20190422_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyTransductor',
            fields=[
                ('serial_number', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=15)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('broken', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(null=True)),
                ('calibration_date', models.DateTimeField(null=True)),
                ('last_data_collection', models.DateTimeField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transductors', to='transductor_models.TransductorModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
