# Generated by Django 2.1.5 on 2019-09-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyTransductor',
            fields=[
                ('serial_number', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=15)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('broken', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('calibration_date', models.DateTimeField(blank=True, null=True)),
                ('last_data_collection', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(default='EnergyTransductor', max_length=256)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transductors.energytransductor_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
