# Generated by Django 3.0.2 on 2020-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='id_in_slave',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
