# Generated by Django 2.1.5 on 2019-04-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transductors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transductors.energytransductor_set+', to='contenttypes.ContentType'),
        ),
    ]
