# Generated by Django 2.1.5 on 2020-01-13 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0002_auto_20190930_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energytransductor',
            old_name='latitude',
            new_name='geolocation_latitude',
        ),
        migrations.RenameField(
            model_name='energytransductor',
            old_name='longitude',
            new_name='geolocation_longitude',
        ),
        migrations.RenameField(
            model_name='energytransductor',
            old_name='location',
            new_name='physical_location',
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='last_data_collection',
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='firmware_version',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ip_address', message='Incorrect IP address format', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$')]),
        ),
    ]
