# Generated by Django 3.0.2 on 2020-04-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('transductors', '0002_auto_20200407_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='grouping',
            field=models.ManyToManyField(blank=True, help_text='This field is required', null=True, to='groups.Group', verbose_name='Grouping'),
        ),
    ]
