# Generated by Django 2.1.5 on 2020-01-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0001_initial'),
        ('transductors', '0003_auto_20200113_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='campi.Campus'),
            preserve_default=False,
        ),
    ]
