# Generated by Django 2.1.5 on 2019-07-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0003_auto_20190520_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.ForeignKey(db_column='model_code', on_delete=django.db.models.deletion.PROTECT, related_name='transductors', to='transductor_models.TransductorModel'),
        ),
    ]
