# Generated by Django 3.0.2 on 2020-01-29 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0003_auto_20200113_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='broken',
            field=models.BooleanField(default=True, verbose_name='unreachable'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='calibration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='calibrated at'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='firmware_version',
            field=models.CharField(max_length=20, verbose_name='firmware version'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='geolocation_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='geolocation_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ip_address', message='Incorrect IP address format', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$')], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.CharField(max_length=256, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='physical_location',
            field=models.CharField(blank=True, max_length=256, verbose_name='Physical location'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='serial_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='serial number'),
        ),
    ]
