# Generated by Django 3.0.2 on 2020-04-07 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0003_auto_20200407_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='serial_number',
            field=models.CharField(help_text='This field is required', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='serial number'),
        ),
    ]
