# Generated by Django 3.0.2 on 2020-02-11 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0004_energytransductor_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='last_minutely_collection',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='last_monthly_collection',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='energytransductor',
            name='last_quarterly_collection',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
