# Generated by Django 2.1.5 on 2019-07-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0004_auto_20190717_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.ForeignKey(db_column='model_code', on_delete=django.db.models.deletion.CASCADE, related_name='transductors', to='transductor_models.TransductorModel'),
        ),
    ]
