# Generated by Django 3.0.2 on 2020-01-29 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0004_auto_20200129_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energytransductor',
            options={'verbose_name': 'Energy meter'},
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='calibration_date',
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='physical_location',
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='broken',
            field=models.BooleanField(default=False, verbose_name='unreachable'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 10, 48, 6, 234285), verbose_name='created at'),
        ),
    ]
