# Generated by Django 3.0.2 on 2020-01-29 15:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0004_auto_20200129_1503'),
        ('transductors', '0004_energytransductor_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energytransductor',
            options={'verbose_name': 'Energy meter'},
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='calibration_date',
        ),
        migrations.RemoveField(
            model_name='energytransductor',
            name='physical_location',
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='broken',
            field=models.BooleanField(default=False, verbose_name='unreachable'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campi.Campus', verbose_name='campus'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 15, 3, 21, 165083), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='firmware_version',
            field=models.CharField(max_length=20, verbose_name='firmware version'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='geolocation_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='geolocation_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ip_address', message='Incorrect IP address format', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$')], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.CharField(max_length=256, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='serial_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='serial number'),
        ),
    ]
