# Generated by Django 3.0.2 on 2020-04-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
        ('transductors', '0004_auto_20200407_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='slave_server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transductors', to='slaves.Slave', verbose_name='Collection Server'),
        ),
    ]
