# Generated by Django 3.0.2 on 2020-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('transductors', '0004_energytransductor_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='grouping',
            field=models.ManyToManyField(help_text='This field is required', to='groups.Group', verbose_name='Grouping'),
        ),
    ]
