# Generated by Django 2.1.5 on 2019-08-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0005_auto_20190730_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.ForeignKey(db_column='model_code', on_delete=django.db.models.deletion.PROTECT, related_name='transductors', to='transductor_models.TransductorModel'),
        ),
    ]
