# Generated by Django 3.0.2 on 2020-01-29 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0007_auto_20200129_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 15, 14, 13, 262397), verbose_name='created at'),
        ),
    ]
