# Generated by Django 3.0.2 on 2020-01-29 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campi', '0005_auto_20200129_1635'),
        ('transductors', '0010_auto_20200129_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransductor',
            name='campus',
            field=models.ForeignKey(help_text='This field is required', on_delete=django.db.models.deletion.CASCADE, to='campi.Campus', verbose_name='campus'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='firmware_version',
            field=models.CharField(help_text='This field is required', max_length=20, verbose_name='firmware version'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', help_text='This field is required', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ip_address', message='Incorrect IP address format', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$')], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='model',
            field=models.CharField(help_text='This field is required', max_length=256, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='name',
            field=models.CharField(blank=True, help_text='This field is required', max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='energytransductor',
            name='serial_number',
            field=models.CharField(help_text='This field is required', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='serial number'),
        ),
    ]
