# Generated by Django 3.0.2 on 2020-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0011_auto_20200129_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='port',
            field=models.IntegerField(default=1001, help_text='This field is required', verbose_name='port'),
        ),
    ]
