# Generated by Django 3.0.2 on 2020-02-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0012_energytransductor_port'),
        ('transductors', '0005_energytransductor_grouping'),
    ]

    operations = [
    ]
