# Generated by Django 3.0.2 on 2020-02-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transductors', '0005_auto_20200211_1659'),
        ('transductors', '0013_merge_20200204_1855'),
    ]

    operations = [
    ]
