# Generated by Django 3.0.2 on 2020-03-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0006_remove_slave_transductors'),
        ('transductors', '0015_auto_20200217_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytransductor',
            name='slave_server',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='slaves.Slave', verbose_name='Collection Server'),
        ),
    ]
